<a href="https://colab.research.google.com/github/hikaruyaku/KIKAGAKU-/blob/master/5_2_%E3%83%8D%E3%83%83%E3%83%88%E3%83%AF%E3%83%BC%E3%82%AF%E3%81%AE%E5%AE%9A%E7%BE%A9%E3%81%A8%E7%B4%94%E4%BC%9D%E6%92%AD%E3%81%AE%E8%A8%88%E7%AE%97.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ネットワークの定義と純伝播の計算

### 1. 環境構築

In [1]:
import torch

In [2]:
torch.__version__

'1.7.0+cu101'

In [3]:
#!pip install torch==1.7.0+cu101

### 2. ネットワークの定義

In [4]:
import torch.nn as nn

In [6]:
# 3 ノード → 2 ノードの全結合層
fc = nn.Linear(3,2)
fc

Linear(in_features=3, out_features=2, bias=True)

In [8]:
# 重み
fc.weight

Parameter containing:
tensor([[ 0.0496, -0.5679, -0.2258],
        [ 0.3022,  0.4305,  0.1337]], requires_grad=True)

In [9]:
# バイアス
fc.bias

Parameter containing:
tensor([0.1166, 0.0059], requires_grad=True)

In [10]:
# 乱数のシードを固定
torch.manual_seed(0)

In [11]:
fc = nn.Linear(3,2)

In [12]:
fc.weight

Parameter containing:
tensor([[-0.0043,  0.3097, -0.4752],
        [-0.4249, -0.2224,  0.1548]], requires_grad=True)

In [13]:
fc.bias

Parameter containing:
tensor([-0.0114,  0.4578], requires_grad=True)

### 3. 線形変換

In [14]:
fc

Linear(in_features=3, out_features=2, bias=True)

In [18]:
x = torch.Tensor([1.,2.,3.])
x

tensor([1., 2., 3.])

In [19]:
type(x)

torch.Tensor

In [20]:
x.dtype

torch.float32

In [23]:
# 線形変換
#fc.__call__(x)
u = fc(x)
u

tensor([-0.8219,  0.0526], grad_fn=<AddBackward0>)

### 4.非線形変換

In [24]:
import torch.nn.functional as F

In [26]:
h = F.relu(u)
h

tensor([0.0000, 0.0526], grad_fn=<ReluBackward0>)

### 5. 目的関数

目的関数 = 損失関数 + 正則化項

In [27]:
# 目標値
t = torch.Tensor([[1],[3]])

In [28]:
# 予測値
y = torch.Tensor([[2],[4]])

In [29]:
# 平均二乗誤差
F.mse_loss(y,t)

tensor(1.)

### 6. nn と F の使い分け

- `nn`: `torch.nn` → パラメータを持つ
- `F` : `torch.nn.function`　→ パラメータを持たない

### テスト問題

In [44]:
# Q1
# 乱数のシード指定
torch.manual_seed(0)

# 各関数のインスタンス化
fc1 = nn.Linear(3,2)
fc2 = nn.Linear(2,1)
h = F.relu(u)

# x のインスタンス化
x = torch.Tensor([1,2,3])

In [45]:
u = fc1(x)
u

tensor([-0.8219,  0.0526], grad_fn=<AddBackward0>)

In [46]:
h = F.relu(u)
h

tensor([0.0000, 0.0526], grad_fn=<ReluBackward0>)

In [47]:
t = fc2(h)
t

tensor([-0.2039], grad_fn=<AddBackward0>)

In [48]:
# q2
# 目標値の定義
y = torch.Tensor([1])

# 平均二乗誤差の算出
F.mse_loss(y,t)

tensor(1.4493, grad_fn=<MseLossBackward>)