<a href="https://colab.research.google.com/github/hikaruyaku/KIKAGAKU-/blob/master/%E3%83%8B%E3%83%A5%E3%83%BC%E3%83%A9%E3%83%AB%E3%83%8D%E3%83%83%E3%83%88%E3%83%AF%E3%83%BC%E3%82%AF%E3%81%AE%E5%AE%9F%E8%A3%85(%E5%88%86%E9%A1%9E).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# ライブラリのインストール
!pip install torch torchvision
!pip install pytorch_lightning

## データセットの準備

In [0]:
import numpy as np
import pandas as pd

In [10]:
from google.colab import files
upload = files.upload()

Saving wine_class.csv to wine_class.csv


In [11]:
# データの読込
df = pd.read_csv("wine_class.csv")

# データの表示
df.head()

Class  Alcohol   Ash  ...  Color intensity   Hue  Proline
0      1    14.23  2.43  ...             5.64  1.04     1065
1      1    13.20  2.14  ...             4.38  1.05     1050
2      1    13.16  2.67  ...             5.68  1.03     1185
3      1    14.37  2.50  ...             7.80  0.86     1480
4      1    13.24  2.87  ...             4.32  1.04      735

[5 rows x 11 columns]

In [15]:
# 入力変数と目的変数に切り分け
np.unique(df['Class'],return_counts=True)

(array([1, 2, 3]), array([59, 71, 48]))

In [17]:
x = df.drop('Class', axis=1)
t = df['Class']

# 表示して確認
x.head(3)

Alcohol   Ash  Alcalinity of ash  ...  Color intensity   Hue  Proline
0    14.23  2.43               15.6  ...             5.64  1.04     1065
1    13.20  2.14               11.2  ...             4.38  1.05     1050
2    13.16  2.67               18.6  ...             5.68  1.03     1185

[3 rows x 10 columns]

In [18]:
#サイズの確認
x.shape, t.shape

((178, 10), (178,))

In [19]:
type(x),type(t)

(pandas.core.frame.DataFrame, pandas.core.series.Series)

In [0]:
import torch

In [21]:
# Tensor 形式へ変換
x = torch.tensor(x.values, dtype=torch.float32)
t = torch.tensor(t.values, dtype=torch.int64)
t

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [22]:
# ラベルを 0 から始める
t = t - 1
t

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [23]:
import torch.utils.data

# 入力変数と目的変数をまとめて、ひとつのオブジェクト dataset に変換
dataset = torch.utils.data.TensorDataset(x, t)
dataset

In [24]:
# (入力変数, 目的変数) のようにタプルで格納されている
dataset[0]

(tensor([1.4230e+01, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00, 3.0600e+00,
         2.8000e-01, 5.6400e+00, 1.0400e+00, 1.0650e+03]), tensor(0))