<a href="https://colab.research.google.com/github/hikaruyaku/KIKAGAKU-/blob/master/%E3%83%8B%E3%83%A5%E3%83%BC%E3%83%A9%E3%83%AB%E3%83%8D%E3%83%83%E3%83%88%E3%83%AF%E3%83%BC%E3%82%AF%E3%81%AE%E5%AE%9F%E8%A3%85(%E5%88%86%E9%A1%9E).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# ライブラリのインストール
!pip install torch torchvision
!pip install pytorch_lightning

## データセットの準備

In [0]:
import numpy as np
import pandas as pd

In [4]:
from google.colab import files
upload = files.upload()

Saving wine_class.csv to wine_class (1).csv


In [5]:
# データの読込
df = pd.read_csv("wine_class.csv")

# データの表示
df.head()

Class  Alcohol   Ash  ...  Color intensity   Hue  Proline
0      1    14.23  2.43  ...             5.64  1.04     1065
1      1    13.20  2.14  ...             4.38  1.05     1050
2      1    13.16  2.67  ...             5.68  1.03     1185
3      1    14.37  2.50  ...             7.80  0.86     1480
4      1    13.24  2.87  ...             4.32  1.04      735

[5 rows x 11 columns]

In [6]:
# 入力変数と目的変数に切り分け
np.unique(df['Class'],return_counts=True)

(array([1, 2, 3]), array([59, 71, 48]))

In [7]:
x = df.drop('Class', axis=1)
t = df['Class']

# 表示して確認
x.head(3)

Alcohol   Ash  Alcalinity of ash  ...  Color intensity   Hue  Proline
0    14.23  2.43               15.6  ...             5.64  1.04     1065
1    13.20  2.14               11.2  ...             4.38  1.05     1050
2    13.16  2.67               18.6  ...             5.68  1.03     1185

[3 rows x 10 columns]

In [8]:
#サイズの確認
x.shape, t.shape

((178, 10), (178,))

In [9]:
type(x),type(t)

(pandas.core.frame.DataFrame, pandas.core.series.Series)

In [0]:
import torch

In [11]:
# Tensor 形式へ変換
x = torch.tensor(x.values, dtype=torch.float32)
t = torch.tensor(t.values, dtype=torch.int64)
t

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [12]:
# ラベルを 0 から始める
t = t - 1
t

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
import torch.utils.data

# 入力変数と目的変数をまとめて、ひとつのオブジェクト dataset に変換
dataset = torch.utils.data.TensorDataset(x, t)
dataset

In [14]:
# (入力変数, 目的変数) のようにタプルで格納されている
dataset[0]

(tensor([1.4230e+01, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00, 3.0600e+00,
         2.8000e-01, 5.6400e+00, 1.0400e+00, 1.0650e+03]), tensor(0))

In [15]:
# 各データセットのサンプル数を決定
# train : val : test = 60% : 20% : 20%
n_train = int(len(dataset) * 0.6)
n_val = int((len(dataset) - n_train) * 0.5)
n_test = len(dataset) - n_train - n_val

# サンプル数の確認

n_train, n_val, n_test

(106, 36, 36)

In [0]:
# ランダムに分割を行うため、シードを固定して再現性を確保
torch.manual_seed(0)

# データセットの分割
train, val, test = torch.utils.data.random_split(dataset, [n_train, n_val, n_test])

## `Pytorch Lightning`によるモデルと学習手順の定義

In [17]:
import pytorch_lightning as pl

# バージョンの確認
pl.__version__

'0.7.5'

In [0]:
import torch.nn as nn
import torch.nn.functional as F

In [0]:
import torch.nn as nn
import torch.nn.functional as F

In [0]:
class Net(pl.LightningModule):
    
    # New: バッチサイズ等を引数に指定
    def __init__(self, input_size=10, hidden_size=5, output_size=3, batch_size=10):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, output_size)
        self.batch_size = batch_size
    
    # 変更なし
    def forward(self, x):
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        return x
    
    # New: 目的関数の設定
    def lossfun(self, y, t):
        return F.cross_entropy(y, t)
    
    # New: optimizer の設定
    def configure_optimizers(self):
        return torch.optim.SGD(self.parameters(), lr=0.1)
    
    # New: train 用の DataLoader の設定
    @pl.data_loader
    def train_dataloader(self):
        return torch.utils.data.DataLoader(train, self.batch_size, shuffle=True)
    
    # New: 学習データに対する処理
    def training_step(self, batch, batch_nb):
        x, t = batch
        y = self.forward(x)
        loss = self.lossfun(y, t)
        results = {'loss': loss}
        return results

In [0]:
# additional: GPUを使用するため
use_cuda = torch.cuda.is_available() and True
device = torch.device("cuda" if use_cuda else "cpu")

In [22]:
# モデルの学習

from pytorch_lightning import  Trainer

# 乱数のシード固定
torch.manual_seed(0)

# インスタンス化
net = Net()

# 学習用に用いるクラスの Trainer をインスタンス化
trainer = Trainer()

# Trainer によるモデルの学習
trainer.fit(net)

INFO:lightning:GPU available: True, used: False
INFO:lightning:
  | Name | Type   | Params
----------------------------
0 | fc1  | Linear | 55    
1 | fc2  | Linear | 18    
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:23: UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)


1