<a href="https://colab.research.google.com/github/hikaruyaku/KIKAGAKU-/blob/master/%E3%83%8B%E3%83%A5%E3%83%BC%E3%83%A9%E3%83%AB%E3%83%8D%E3%83%83%E3%83%88%E3%83%AF%E3%83%BC%E3%82%AF%E3%81%AE%E5%AE%9F%E8%A3%85(%E5%88%86%E9%A1%9E).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
# ライブラリのインストール
!pip install torch torchvision
!pip install pytorch_lightning

## データセットの準備

In [0]:
import numpy as np
import pandas as pd

In [25]:
from google.colab import files
upload = files.upload()

Saving wine_class.csv to wine_class (2).csv


In [26]:
# データの読込
df = pd.read_csv("wine_class.csv")

# データの表示
df.head()

Class  Alcohol   Ash  ...  Color intensity   Hue  Proline
0      1    14.23  2.43  ...             5.64  1.04     1065
1      1    13.20  2.14  ...             4.38  1.05     1050
2      1    13.16  2.67  ...             5.68  1.03     1185
3      1    14.37  2.50  ...             7.80  0.86     1480
4      1    13.24  2.87  ...             4.32  1.04      735

[5 rows x 11 columns]

In [27]:
# 入力変数と目的変数に切り分け
np.unique(df['Class'],return_counts=True)

(array([1, 2, 3]), array([59, 71, 48]))

In [28]:
x = df.drop('Class', axis=1)
t = df['Class']

# 表示して確認
x.head(3)

Alcohol   Ash  Alcalinity of ash  ...  Color intensity   Hue  Proline
0    14.23  2.43               15.6  ...             5.64  1.04     1065
1    13.20  2.14               11.2  ...             4.38  1.05     1050
2    13.16  2.67               18.6  ...             5.68  1.03     1185

[3 rows x 10 columns]

In [29]:
#サイズの確認
x.shape, t.shape

((178, 10), (178,))

In [30]:
type(x),type(t)

(pandas.core.frame.DataFrame, pandas.core.series.Series)

In [0]:
import torch

In [32]:
# Tensor 形式へ変換
x = torch.tensor(x.values, dtype=torch.float32)
t = torch.tensor(t.values, dtype=torch.int64)
t

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [33]:
# ラベルを 0 から始める
t = t - 1
t

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [34]:
import torch.utils.data

# 入力変数と目的変数をまとめて、ひとつのオブジェクト dataset に変換
dataset = torch.utils.data.TensorDataset(x, t)
dataset

In [35]:
# (入力変数, 目的変数) のようにタプルで格納されている
dataset[0]

(tensor([1.4230e+01, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00, 3.0600e+00,
         2.8000e-01, 5.6400e+00, 1.0400e+00, 1.0650e+03]), tensor(0))

In [36]:
# 各データセットのサンプル数を決定
# train : val : test = 60% : 20% : 20%
n_train = int(len(dataset) * 0.6)
n_val = int((len(dataset) - n_train) * 0.5)
n_test = len(dataset) - n_train - n_val

# サンプル数の確認

n_train, n_val, n_test

(106, 36, 36)

In [0]:
# ランダムに分割を行うため、シードを固定して再現性を確保
torch.manual_seed(0)

# データセットの分割
train, val, test = torch.utils.data.random_split(dataset, [n_train, n_val, n_test])

## `Pytorch Lightning`によるモデルと学習手順の定義

In [38]:
import pytorch_lightning as pl

# バージョンの確認
pl.__version__

'0.7.5'

In [0]:
import torch.nn as nn
import torch.nn.functional as F

In [0]:
import torch.nn as nn
import torch.nn.functional as F

In [0]:
class Net(pl.LightningModule):
    
    # New: バッチサイズ等を引数に指定
    def __init__(self, input_size=10, hidden_size=5, output_size=3, batch_size=10):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, output_size)
        self.batch_size = batch_size
    
    # 変更なし
    def forward(self, x):
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        return x
    
    # New: 目的関数の設定
    def lossfun(self, y, t):
        return F.cross_entropy(y, t)
    
    # New: optimizer の設定
    def configure_optimizers(self):
        return torch.optim.SGD(self.parameters(), lr=0.1)
    
    # New: train 用の DataLoader の設定
    @pl.data_loader
    def train_dataloader(self):
        return torch.utils.data.DataLoader(train, self.batch_size, shuffle=True)
    
    # New: 学習データに対する処理
    def training_step(self, batch, batch_nb):
        x, t = batch
        y = self.forward(x)
        loss = self.lossfun(y, t)
        results = {'loss': loss}
        return results

In [44]:
# モデルの学習

from pytorch_lightning import  Trainer

# 乱数のシード固定
torch.manual_seed(0)

# インスタンス化
net = Net()

# 学習用に用いるクラスの Trainer をインスタンス化
# default の max_epochs が 1000 だと一向に進まないので、100に変更
trainer = Trainer(max_epochs=100)

# Trainer によるモデルの学習
trainer.fit(net)

INFO:lightning:GPU available: True, used: False
INFO:lightning:
  | Name | Type   | Params
----------------------------
0 | fc1  | Linear | 55    
1 | fc2  | Linear | 18    
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:23: UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)


1

In [0]:
class Net(pl.LightningModule):

  def __init__(self, input_size=10, hidden_size=5, output_size=3, batch_size=10):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(input_size, hidden_size)
    self.fc2 = nn.Linear(hidden_size, output_size)
    self.batch_size = batch_size

  def forward(self, x):
    x = self.fc1(x)
    x = F.relu(x)
    x = self.fc2(x)
    return x

  def lossfun(self, y, t):
    return F.cross_entropy(y, t)

  def configure_optimizers(self):
    return torch.optim.SGD(self.parameters(),lr=0.1)

  @pl.data_loader
  def train_dataloader(self):
    return torch.utils.data.DataLoader(train, self.batch_size, shuffle=True)

  def training_step(self, batch, batch_nb):
    x, t = batch
    y = self.forward(x)
    loss = self.lossfun(y, t)
    results = {"loss" : loss}
    return results

  # New: 検証用データセットの設定
  @pl.data_loader
  def val_dataloader(self):
    return torch.utils.data.DataLoader(val, self.batch_size)

  # New: 検証データに対するイテレーションごとの処理
  def validation_step(self, batch, batch_nb):
    x, t = batch
    y = self.forward(x)
    loss = self.lossfun(y, t)

    # 正解率の導出
    y_label = torch.argmax(y, dim=1)
    acc = torch.sum(t == y_label) * 1.0 / len(t)
    results = {"val_loss" : loss, "val_acc" : acc}
    return results
  
  # New: 検証データに対するエポックごとの処理
  def validation_end(self, outputs):
    # 各イテレーションごとに得られた値をまとめて、平均値の取得
    avg_loss = torch.stack([x["val_loss"] for x in outputs]).mean()
    avg_acc  = torch.stack([x["val_acc"] for x in outputs]).mean()
    results = {"val_loss" : avg_loss, "val_acc" : avg_acc}
    return results

In [46]:
torch.manual_seed(0)

net = Net()
trainer = Trainer(max_epochs=100)

# モデルの学習
trainer.fit(net)

INFO:lightning:GPU available: True, used: False
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:23: RuntimeWarning: You have defined a `val_dataloader()` and have defined a `validation_step()`, you may also want to define `validation_epoch_end()` for accumulating stats.
  warnings.warn(*args, **kwargs)
INFO:lightning:
  | Name | Type   | Params
----------------------------
0 | fc1  | Linear | 55    
1 | fc2  | Linear | 18    
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:23: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)


/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:23: UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)


1

In [0]:
class Net(pl.LightningModule):

    def __init__(self, input_size=10, hidden_size=5, output_size=3, batch_size=10):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, output_size)
        self.batch_size = batch_size

    def forward(self, x):
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        return x

    def lossfun(self, y, t):
        return F.cross_entropy(y, t)
    
    def configure_optimizers(self):
        return torch.optim.SGD(self.parameters(), lr=0.1)
    
    @pl.data_loader
    def train_dataloader(self):
        return torch.utils.data.DataLoader(train, self.batch_size, shuffle=True)
    
    def training_step(self, batch, batch_nb):
        x, t = batch
        y = self.forward(x)
        loss = self.lossfun(y, t)
        results = {'loss': loss}
        return results
    
    @pl.data_loader
    def val_dataloader(self):
        return torch.utils.data.DataLoader(val, self.batch_size)
    
    def validation_step(self, batch, batch_nb):
        x, t = batch
        y = self.forward(x)
        loss = self.lossfun(y, t)
        y_label = torch.argmax(y, dim=1)
        acc = torch.sum(t == y_label) * 1.0 / len(t)        
        results = {'val_loss': loss, 'val_acc': acc}
        return results
    
    def validation_end(self, outputs):
        avg_loss = torch.stack([x['val_loss'] for x in outputs]).mean()
        avg_acc  =torch.stack([x['val_acc'] for x in outputs]).mean()
        results = {'val_loss': avg_loss, 'val_acc': avg_acc}
        return results
    
    # New: テストデータセットの設定
    @pl.data_loader
    def test_dataloader(self):
        return torch.utils.data.DataLoader(test, self.batch_size)
    
    # New: テストデータに対するイテレーションごとの処理
    def test_step(self, batch, batch_nb):
        x, t = batch
        y = self.forward(x)
        loss = self.lossfun(y, t)
        y_label = torch.argmax(y, dim=1)
        acc = torch.sum(t == y_label) * 1.0 / len(t)
        results = {'test_loss': loss, 'test_acc': acc}
        return results
    
    # New: テストデータに対するエポックごとの処理
    def test_end(self, outputs):
        avg_loss = torch.stack([x['test_loss'] for x in outputs]).mean()
        avg_acc = torch.stack([x['test_acc'] for x in outputs]).mean()
        results = {'test_loss': avg_loss, 'test_acc': avg_acc}
        return results

In [49]:
     
# 学習に関する一連の流れを実行
torch.manual_seed(0)

net = Net()
trainer = Trainer(max_epochs=100)

trainer.fit(net)

INFO:lightning:GPU available: True, used: False
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:23: RuntimeWarning: You have defined a `val_dataloader()` and have defined a `validation_step()`, you may also want to define `validation_epoch_end()` for accumulating stats.
  warnings.warn(*args, **kwargs)
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:23: RuntimeWarning: You have defined a `test_dataloader()` and have defined a `test_step()`, you may also want to define `test_epoch_end()` for accumulating stats.
  warnings.warn(*args, **kwargs)
INFO:lightning:
  | Name | Type   | Params
----------------------------
0 | fc1  | Linear | 55    
1 | fc2  | Linear | 18    
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:23: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` in the `D

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:23: UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)


1

In [50]:
# テストデータに対する処理の実行(test_step と　test_end)
trainer.test()

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:23: RuntimeWarning: You passed  in a `test_dataloader` and have defined a `test_step()`, you may also want to define `test_epoch_end()` for accumulating stats.
  warnings.warn(*args, **kwargs)
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:23: UserWarning: The dataloader, test dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)


--------------------------------------------------------------------------------
TEST RESULTS
{'test_acc': tensor(0.4500), 'test_loss': tensor(1.0763)}
--------------------------------------------------------------------------------



In [51]:
# テストデータに対する結果の確認
trainer.callback_metrics

{'epoch': 99,
 'loss': tensor(1.1056),
 'test_acc': tensor(0.4500),
 'test_loss': tensor(1.0763),
 'val_acc': tensor(0.3917),
 'val_loss': tensor(1.0849)}

## 可読性と汎用性を向上  

`class NET`はそのままに、それ以降のクラスを学習、検証、テストに分割する。

In [65]:
# additional: GPUを使用するため
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cuda', index=0)

In [0]:
# 学習データに対する処理
class TrainNet(pl.LightningModule):

  @pl.data_loader
  def train_dataloader(self):
    return torch.utils.data.DataLoader(train, self.batch_size, shuffle=True)

  def training_step(self, batch, batch_nb):
    x,t = batch
    x = x.to(device)
    t = t.to(device)
    y = self.forward(x)
    loss = self.lossfun(y,t)
    results = {"loss" : loss}
    return results

In [0]:
# 検証データに対する処理
class ValidationNet(pl.LightningModule):

  @pl.data_loader
  def val_dataloader(self):
    return torch.utils.data.DataLoader(val, self.batch_size)

  def validation_step(self, batch, batch_nb):
    x, t = batch
    x = x.to(device)
    t = t.to(device)
    y = self.forward(x)
    loss = self.lossfun(y, t)
    y_label = torch.argmax(y, dim=1)
    acc = torch.sum(t == y_label) * 1.0 /len(t)
    results = {"val_loss" : loss, "val_acc" : acc}
    return results

  def validation_end(self, outputs):
    avg_loss = torch.stack([x["val_loss"] for x in outputs]).mean()
    avg_acc  = torch.stack([x['val_acc' ] for x in outputs]).mean()
    results = {"val_loss" : avg_loss, "val_acc" : avg_acc}
    return results

In [0]:
# テストデータに対する処理
class TestNet(pl.LightningModule):

  @pl.data_loader
  def test_dataloader(self):
    return torch.utils.data.DataLoader(test, self.batch_size)

  def test_step(self, batch, batch_nb):
    x, t = batch
    x = x.to(device)
    t = t.to(device)
    y = self.forward(x)
    loss = self.lossfun(y, t)
    y_label = torch.argmax(y, dim=1)
    acc = torch.sum(t == y_label) * 1.0 / len(t)
    results = {"test_loss" : loss, "test_acc" : acc}
    return results

  def test_end(self, outputs):
    avg_loss = torch.stack([x["test_loss"] for x in outputs]).mean()
    avg_acc  = torch.stack([x["test_acc" ] for x in outputs]).mean()
    results = {"test_loss" : avg_loss, "test_acc" : avg_acc}
    return results

In [0]:
# 学習データ、検証データ、テストデータへの処理を継承したクラス
class Net(TrainNet, ValidationNet, TestNet):

  def __init__(self, input_size=10, hidden_size=5, output_size=3, batch_size=10):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(input_size, hidden_size)
    self.fc2 = nn.Linear(hidden_size, output_size)
    self.batch_size = batch_size

  def forward(self, x):
    x = self.fc1(x)
    x = F.relu(x)
    x = self.fc2(x)
    return x

  def lossfun(self, y, t):
    return F.cross_entropy(y, t)

  def configure_optimizers(self):
    return torch.optim.SGD(self.parameters(), lr=0.1)

In [87]:
# 学習に関する一連の流れを実行
torch.manual_seed(0)

net = Net().to(device)
trainer = Trainer(max_epochs=100)

trainer.fit(net)

INFO:lightning:GPU available: True, used: False
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:23: RuntimeWarning: You have defined a `val_dataloader()` and have defined a `validation_step()`, you may also want to define `validation_epoch_end()` for accumulating stats.
  warnings.warn(*args, **kwargs)
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:23: RuntimeWarning: You have defined a `test_dataloader()` and have defined a `test_step()`, you may also want to define `test_epoch_end()` for accumulating stats.
  warnings.warn(*args, **kwargs)
INFO:lightning:
  | Name | Type   | Params
----------------------------
0 | fc1  | Linear | 55    
1 | fc2  | Linear | 18    
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:23: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` in the `D

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:23: UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)


1

In [88]:
# テストデータに対する処理の実行 (test_step と test_end)
trainer.test()

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:23: RuntimeWarning: You passed  in a `test_dataloader` and have defined a `test_step()`, you may also want to define `test_epoch_end()` for accumulating stats.
  warnings.warn(*args, **kwargs)
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:23: UserWarning: The dataloader, test dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)


--------------------------------------------------------------------------------
TEST RESULTS
{'test_acc': tensor(0.4500, device='cuda:0'),
 'test_loss': tensor(1.0763, device='cuda:0')}
--------------------------------------------------------------------------------



In [89]:
# 結果の確認
trainer.callback_metrics

{'epoch': 99,
 'loss': tensor(1.1056, device='cuda:0'),
 'test_acc': tensor(0.4500, device='cuda:0'),
 'test_loss': tensor(1.0763, device='cuda:0'),
 'val_acc': tensor(0.3917, device='cuda:0'),
 'val_loss': tensor(1.0849, device='cuda:0')}

## 学習済モデルの保存から推論

In [96]:
# モデルの重み
net.state_dict()

OrderedDict([('fc1.weight',
              tensor([[-8.1171e-02,  1.5609e-01, -3.2934e-01, -8.5862e-01, -1.4343e-01,
                        6.3875e-02, -6.1343e-03,  2.1071e-01, -3.4258e-02, -9.6708e+00],
                      [-9.5568e-02, -6.2159e-02, -3.0211e-01, -2.0943e-01, -1.3036e-01,
                        1.1714e-02,  1.2502e-01,  1.8974e-01, -2.1438e-01, -1.3771e-01],
                      [ 1.1486e-01,  2.6259e-01, -6.5080e-02,  2.3664e-01, -5.0971e-02,
                        3.3461e-02,  2.8634e-01, -2.9336e-01, -1.9908e-01, -8.0058e-02],
                      [-5.5308e-01,  1.9758e-01, -7.5457e-01, -3.3142e+00, -3.0678e-01,
                       -3.8247e-01, -1.9462e-01,  1.1357e-01,  1.0854e-01, -3.3783e+01],
                      [ 1.6631e-02, -1.6212e-01,  5.3501e-02, -2.9526e-01, -2.2850e-01,
                       -1.6302e-01,  1.9952e-01,  1.8541e-01, -1.4025e-01, -1.1410e-02]])),
             ('fc1.bias', tensor([0.1968, 0.3144, 0.1255, 0.0107, 0.2120])),
       

In [0]:
# 学習済モデルを保存
torch.save(net.state_dict(), "wine.pt")

In [0]:
# インスタンス化
net = Net()

In [99]:
net.load_state_dict(torch.load("wine.pt"))

<All keys matched successfully>

In [100]:
# 予測値の計算
y = net(x)[0]
y

RuntimeError: ignored

In [95]:
# 予測ラベル
torch.argmax(y)

NameError: ignored

In [101]:
t[0]

tensor(0, device='cuda:0')